######################################################################
# Automatically generated by qmake (3.1) Wed Feb 8 21:12:34 2017
######################################################################

TEMPLATE = app
TARGET = utils
INCLUDEPATH += .
QT -= gui
# Input
SOURCES += nfqnl_test.c
LIBS += -lnetfilter_queue
